import type { Metadata } from 'next';
import { Sora, Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/site/Navbar';
import ClientLayout from '@/components/site/ClientLayout';
import { Footer } from '@/components/site/Footer';

const sora = Sora({
  variable: '--font-display',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${sora.variable} ${inter.variable} h-full antialiased`}>
      <body className='min-h-full flex flex-col'>
        <ClientLayout>
          <Navbar />
          <main className='flex-1'>{children}</main>
          <Footer />
        </ClientLayout>
      </body>
    </html>
  );
}
